# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy ASP app to Azure Web App - gsm-stuartdemo-redirect-4vemwq4qhdtpk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        with:
          name: ASP-app
          
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9E17AD554CCE46E1B021F24C8046BCDC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_48DA54AB9D4A4B73BAF7362572061F79 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4B2012E9018B4C668C4245784AE262E8 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'gsm-stuartdemo-redirect-4vemwq4qhdtpk'
          slot-name: 'Production'
          package: .
          steps: